const jordanInsight = {
    hangoutLikelihood: 0.88,
    reliabilityLabel: "usually follows through",
    cadenceNote: "You two usually click tonight",
    clusterLabel: "Same NYU",
    lastSignal: "FREE_NOW",
    momentumLabel: "recently active",
};
const minaInsight = {
    hangoutLikelihood: 0.72,
    reliabilityLabel: "better with softer invites",
    cadenceNote: "Best with casual, low-pressure invites",
    clusterLabel: "Brooklyn crew",
    lastSignal: "FREE_LATER",
    momentumLabel: "steady rhythm",
};
export const demoUser = {
    id: "user-avery",
    inviteCode: "invite-avery",
    name: "Avery",
    city: "New York",
    onboardingCompleted: true,
    photoUrl: null,
    phone: "+15550000001",
    responsivenessScore: 0.89,
    discordUsername: "averyloop",
    communityTag: "NYU",
    sharedServerCount: 3,
    streakCount: 4,
    invitesSent: 7,
    premium: false,
    hasDiscordLinked: true,
    notificationIntensity: "BALANCED",
};
export const demoFriends = [
    {
        id: "user-jordan",
        friendshipId: "friend-jordan",
        name: "Jordan",
        city: "Lower East Side",
        photoUrl: null,
        phone: "+15550000002",
        responsivenessScore: 0.83,
        discordUsername: "jordango",
        communityTag: "NYU",
        sharedServerCount: 2,
        status: "ACCEPTED",
        lastSignal: "FREE_NOW",
        sharedLabel: "You share 2 servers",
        insight: jordanInsight,
        requestDirection: null,
    },
    {
        id: "user-mina",
        friendshipId: "friend-mina",
        name: "Mina",
        city: "Brooklyn",
        photoUrl: null,
        phone: "+15550000003",
        responsivenessScore: 0.75,
        communityTag: "Brooklyn crew",
        sharedServerCount: 1,
        status: "ACCEPTED",
        lastSignal: "FREE_LATER",
        sharedLabel: "You share a server",
        insight: minaInsight,
        requestDirection: null,
    },
    {
        id: "user-leo",
        friendshipId: "friend-leo",
        name: "Leo",
        city: "Queens",
        photoUrl: null,
        phone: "+15550000004",
        responsivenessScore: 0.66,
        communityTag: "Queens nights",
        sharedServerCount: 0,
        status: "PENDING",
        lastSignal: "BUSY",
        requestDirection: "OUTGOING",
    },
    {
        id: "user-sana",
        friendshipId: "friend-sana",
        name: "Sana",
        city: "Williamsburg",
        photoUrl: null,
        phone: "+15550000005",
        responsivenessScore: 0.8,
        communityTag: "Brooklyn crew",
        sharedServerCount: 1,
        status: "PENDING",
        lastSignal: "FREE_LATER",
        sharedLabel: "You share a server",
        requestDirection: "INCOMING",
    },
];
export const demoSuggestions = [
    {
        id: "user-nora",
        friendshipId: "suggestion-nora",
        name: "Nora",
        city: "East Village",
        photoUrl: null,
        phone: "+15550000006",
        responsivenessScore: 0.77,
        communityTag: "NYU",
        sharedServerCount: 2,
        status: "PENDING",
        sharedLabel: "Same NYU",
        requestDirection: null,
    },
    {
        id: "user-kai",
        friendshipId: "suggestion-kai",
        name: "Kai",
        city: "Lower East Side",
        photoUrl: null,
        phone: "+15550000007",
        responsivenessScore: 0.71,
        communityTag: "LES nights",
        sharedServerCount: 0,
        status: "PENDING",
        sharedLabel: "Lower East Side crew",
        requestDirection: null,
    },
];
export const demoSignal = {
    id: "signal-avery",
    state: "FREE_NOW",
    label: "Post-class coffee run",
    radiusKm: 8,
    vibe: "COFFEE",
    energyLevel: "MEDIUM",
    budgetMood: "LOW_SPEND",
    socialBattery: "OPEN",
    hangoutIntent: "COFFEE_RUN",
    expiresAt: new Date(Date.now() + 3 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date().toISOString(),
};
export const demoRecurringWindows = [
    {
        id: "window-1",
        recurrence: "WEEKLY",
        dayOfWeek: 2,
        dayOfMonth: null,
        startMinute: 18 * 60,
        endMinute: 20 * 60,
        utcOffsetMinutes: 240,
        label: "Tuesday after class",
        vibe: "COFFEE",
        hangoutIntent: "COFFEE_RUN",
        createdAt: new Date().toISOString(),
    },
    {
        id: "window-2",
        recurrence: "WEEKLY",
        dayOfWeek: 5,
        dayOfMonth: null,
        startMinute: 19 * 60,
        endMinute: 22 * 60,
        utcOffsetMinutes: 240,
        label: "Friday night window",
        vibe: "FOOD",
        hangoutIntent: "QUICK_BITE",
        createdAt: new Date().toISOString(),
    },
    {
        id: "window-3",
        recurrence: "MONTHLY",
        dayOfWeek: null,
        dayOfMonth: 15,
        startMinute: 13 * 60,
        endMinute: 16 * 60,
        utcOffsetMinutes: 240,
        label: "Mid-month flex window",
        vibe: "CHILL",
        hangoutIntent: "QUICK_CHILL",
        createdAt: new Date().toISOString(),
    },
];
export const demoMatches = [
    {
        id: "match-jordan",
        score: 0.91,
        reason: {
            overlapMinutes: 122,
            travelMinutes: 12,
            sharedVibe: "FOOD",
            sharedIntent: "QUICK_BITE",
            discordBonus: 0.05,
            relationshipScore: 0.88,
            identityScore: 0.8,
            timingLabel: "tonight",
            momentumLabel: "recently active",
            localDensityLabel: "Same NYU",
        },
        matchedUser: demoFriends[0],
        insightLabel: "recently active",
        availability: demoSignal,
        matchedSignal: {
            id: "signal-jordan",
            state: "FREE_NOW",
            radiusKm: 8,
            vibe: "FOOD",
            energyLevel: "HIGH",
            budgetMood: "FLEXIBLE",
            socialBattery: "SOCIAL",
            hangoutIntent: "QUICK_BITE",
            expiresAt: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
            createdAt: new Date().toISOString(),
        },
        status: "OPEN",
    },
    {
        id: "match-mina",
        score: 0.77,
        reason: {
            overlapMinutes: 188,
            travelMinutes: 18,
            sharedVibe: "CHILL",
            sharedIntent: "QUICK_CHILL",
            discordBonus: 0.03,
            relationshipScore: 0.72,
            identityScore: 0.78,
            timingLabel: "after class",
            momentumLabel: "steady rhythm",
            localDensityLabel: "Brooklyn crew",
        },
        matchedUser: demoFriends[1],
        insightLabel: "steady rhythm",
        availability: demoSignal,
        matchedSignal: {
            id: "signal-mina",
            state: "FREE_LATER",
            radiusKm: 12,
            vibe: "CHILL",
            energyLevel: "LOW",
            budgetMood: "LOW_SPEND",
            socialBattery: "LOW_KEY",
            hangoutIntent: "QUICK_CHILL",
            expiresAt: new Date(Date.now() + 5 * 60 * 60 * 1000).toISOString(),
            createdAt: new Date().toISOString(),
        },
        status: "OPEN",
    },
];
export const demoScheduledOverlaps = [
    {
        id: "scheduled-overlap-jordan",
        score: 0.92,
        startsAt: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000 + 18 * 60 * 60 * 1000).toISOString(),
        endsAt: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000 + 19.5 * 60 * 60 * 1000).toISOString(),
        overlapMinutes: 90,
        matchedUser: demoFriends[0],
        sourceWindow: demoRecurringWindows[0],
        matchedWindow: {
            id: "window-jordan-1",
            recurrence: "WEEKLY",
            dayOfWeek: 2,
            dayOfMonth: null,
            startMinute: 18 * 60 + 30,
            endMinute: 20 * 60,
            utcOffsetMinutes: 240,
            label: "Jordan's Tuesday window",
            vibe: "COFFEE",
            hangoutIntent: "COFFEE_RUN",
            createdAt: new Date().toISOString(),
        },
        label: "Tue · 6:30 PM - 8:00 PM",
        summary: "Jordan also tends to be down for coffee run during this window.",
        sharedVibe: "COFFEE",
        sharedIntent: "COFFEE_RUN",
    },
    {
        id: "scheduled-overlap-mina",
        score: 0.81,
        startsAt: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000 + 19 * 60 * 60 * 1000).toISOString(),
        endsAt: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000 + 21 * 60 * 60 * 1000).toISOString(),
        overlapMinutes: 120,
        matchedUser: demoFriends[1],
        sourceWindow: demoRecurringWindows[1],
        matchedWindow: {
            id: "window-mina-1",
            recurrence: "WEEKLY",
            dayOfWeek: 5,
            dayOfMonth: null,
            startMinute: 18 * 60,
            endMinute: 21 * 60,
            utcOffsetMinutes: 240,
            label: "Mina's Friday flex",
            vibe: "FOOD",
            hangoutIntent: "QUICK_BITE",
            createdAt: new Date().toISOString(),
        },
        label: "Fri · 7:00 PM - 9:00 PM",
        summary: "Mina overlaps on food energy here. You two usually click tonight.",
        sharedVibe: "FOOD",
        sharedIntent: "QUICK_BITE",
    },
];
export const demoHangouts = [
    {
        id: "hangout-ramen",
        activity: "grab ramen",
        microType: "QUICK_BITE",
        commitmentLevel: "QUICK_WINDOW",
        locationName: "St. Marks",
        scheduledFor: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
        status: "CONFIRMED",
        threadId: "thread-ramen",
        participants: [
            {
                userId: demoUser.id,
                responseStatus: "ACCEPTED",
                microResponse: "PULLING_UP",
                etaMinutes: 10,
            },
            {
                userId: demoFriends[0].id,
                responseStatus: "ACCEPTED",
                microResponse: "TEN_MIN_ONLY",
                etaMinutes: 12,
            },
        ],
        participantsInfo: [
            {
                userId: demoUser.id,
                name: demoUser.name,
                responseStatus: "ACCEPTED",
                microResponse: "PULLING_UP",
                etaMinutes: 10,
            },
            {
                userId: demoFriends[0].id,
                name: demoFriends[0].name,
                responseStatus: "ACCEPTED",
                microResponse: "TEN_MIN_ONLY",
                etaMinutes: 12,
            },
        ],
    },
    {
        id: "hangout-group",
        activity: "late coffee crawl",
        microType: "COFFEE_RUN",
        commitmentLevel: "DROP_IN",
        locationName: "West Village",
        scheduledFor: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
        status: "PROPOSED",
        threadId: "thread-group",
        participants: [
            {
                userId: demoUser.id,
                responseStatus: "ACCEPTED",
            },
            {
                userId: demoFriends[0].id,
                responseStatus: "PENDING",
            },
            {
                userId: demoFriends[1].id,
                responseStatus: "PENDING",
            },
        ],
        participantsInfo: [
            {
                userId: demoUser.id,
                name: demoUser.name,
                responseStatus: "ACCEPTED",
            },
            {
                userId: demoFriends[0].id,
                name: demoFriends[0].name,
                responseStatus: "PENDING",
            },
            {
                userId: demoFriends[1].id,
                name: demoFriends[1].name,
                responseStatus: "PENDING",
            },
        ],
    },
];
export const demoThreads = {
    "thread-ramen": [
        {
            id: "message-1",
            threadId: "thread-ramen",
            senderId: demoUser.id,
            senderName: demoUser.name,
            text: "Down for noodles at 8?",
            type: "TEXT",
            createdAt: new Date(Date.now() - 22 * 60 * 1000).toISOString(),
        },
        {
            id: "message-2",
            threadId: "thread-ramen",
            senderId: demoFriends[0].id,
            senderName: demoFriends[0].name,
            text: "Absolutely.",
            type: "TEXT",
            createdAt: new Date(Date.now() - 18 * 60 * 1000).toISOString(),
        },
    ],
    "thread-group": [
        {
            id: "message-3",
            threadId: "thread-group",
            senderId: demoUser.id,
            senderName: demoUser.name,
            text: "Who's free tonight?",
            type: "SYSTEM",
            createdAt: new Date(Date.now() - 6 * 60 * 1000).toISOString(),
        },
    ],
};
export const demoDirectChats = [
    {
        id: "chat-jordan",
        title: null,
        isGroup: false,
        memberCount: 2,
        participants: [demoFriends[0]],
        lastMessageText: "Pulling up in ten.",
        lastMessageAt: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
        createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: "chat-group-crew",
        title: "Friday after class",
        isGroup: true,
        memberCount: 3,
        participants: [demoFriends[0], demoFriends[1]],
        lastMessageText: "Want to lock Friday after class?",
        lastMessageAt: new Date(Date.now() - 46 * 60 * 1000).toISOString(),
        createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    },
];
export const demoDirectMessages = {
    "chat-jordan": [
        {
            id: "chat-msg-1",
            chatId: "chat-jordan",
            senderId: demoFriends[0].id,
            senderName: demoFriends[0].name,
            text: "Pulling up in ten.",
            type: "TEXT",
            createdAt: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
        },
        {
            id: "chat-msg-2",
            chatId: "chat-jordan",
            senderId: demoUser.id,
            senderName: demoUser.name,
            text: "Perfect. Meet outside the spot.",
            type: "TEXT",
            createdAt: new Date(Date.now() - 9 * 60 * 1000).toISOString(),
        },
    ],
    "chat-mina": [
        {
            id: "chat-msg-3",
            chatId: "chat-mina",
            senderId: demoUser.id,
            senderName: demoUser.name,
            text: "Want to lock Friday after class?",
            type: "TEXT",
            createdAt: new Date(Date.now() - 46 * 60 * 1000).toISOString(),
        },
    ],
};
export const demoRecaps = [
    {
        id: "recap-1",
        hangoutId: "hangout-ramen",
        title: "Noodle night streak",
        summary: "Quick plan, real night out, zero overthinking.",
        badge: "Crew made it out",
        streakCount: 4,
        shareLabel: "Share recap",
    },
];
export const demoRadar = {
    rhythm: {
        state: "LIVE",
        headline: "Your crew is moving",
        detail: "2 friends look open around NYU right now.",
        bestWindow: "tonight",
        activeNowCount: 2,
        nearbyFriendsCount: 2,
        cadenceDays: 2,
        livePrompt: "Use a low-pressure prompt before the window fades.",
        communityLabel: "NYU",
    },
    localDensity: {
        communityLabel: "NYU",
        nearbyFriendsCount: 2,
        activeNowCount: 2,
        densityLabel: "local crew building",
    },
    suggestionLine: "Best chance is tonight. Lead with a quick drop-in prompt.",
};
